export const numberInformation = [
  {
    id: "1",
    value: 1,
    riddles: [
      "How many sides does a circle have?",
      "What is the first positive odd number?",
      // "How many hearts does an octopus have?",
      "How many semi-breve notes can fit in a 4/4 time signature bar in music?",
      "What is the atomic number of hydrogen?",
      // "How many sovereign states are members of the United Nations?",
      // "In a binary system, how many digits can represent any number?",
      // "How many solutions does the equation x + 0 = x have?",
    ],
  },
  {
    id: "2",
    value: 2,
    riddles: [
      "In chemistry, what is the atomic number of helium?",
      "In physics, how many poles does a magnet typically have?",
      "How many ears does a human typically have?",
      "How many seasons are there in Indonesia?",
      "How many sides does a coin usually have?",
      // "What is the second digit in the number pi (π)?",
      "How many lungs does a typical human have?",
      // "How many times does the hour hand of a clock rotate in a 24-hour period?",
    ],
  },
  {
    id: "3",
    value: 3,
    riddles: [
      "In literature, how many parts are there in Dante Alighieri's epic poem 'The Divine Comedy'?",
      "How many heads does the Chimera have in Greek mythology?",
      "How many primary colors are there?",
      "How many legs does a tripod typically have?",
      "How many dimensions are typically depicted in a traditional Cartesian coordinate system?",
      "How many sides does a triangle have?",
      "In baseball, how many outs are required to end an inning?",
      "How many wheels does a tricycle typically have?",
    ],
  },
  {
    id: "4",
    value: 4,
    riddles: [
      "In music theory, how many beats are there in a standard musical bar of 4/4 time signature?",
      "In mathematics, what is the square root of 8 multiplied by 4 divided by 2?",
      "How many seasons are there in a year?",
      "How many quarters are there in a dollar?",
      "How many primary taste sensations can the human tongue detect?",
      "How many chambers are there in the human heart?",
      "How many bases are there in baseball?",
      "How many suits are there in a standard deck of playing cards?",
    ],
  },
  {
    id: "5",
    value: 5,
    riddles: [
      "In film, how many Oscars did the movie 'Schindler's List' win in 1994?",
      "In astronomy, how many dwarf planets are officially recognized in our solar system?",
      "How many fingers does a typical human have on one hand?",
      "How many senses does a human typically have?",
      "How many points are scored for a touchdown in American football?",
      "How many Olympic rings are there?",
      "How many Great Lakes are there in North America?",
      "How many vowels are there in the English alphabet?",
    ],
  },
  {
    id: "6",
    value: 6,
    riddles: [
      "How many legs does a termite have?",
      "How many colours are on the South African flag",
      "How many strings does a standard guitar have?",
      "How many faces does a cube have?",
      "How many legs does an insect typically have?",
      "In a standard game of pool, how many pockets are there on the table?",
      "How many main characters are there in the TV show 'Friends'?",
      "How many sides does a hexagon have?",
    ],
  },
  {
    id: "7",
    value: 7,
    riddles: [
      "In folklore, how many seas did Sinbad the Sailor supposedly sail?",
      "In mythology, how many wonders were there in the ancient world according to the classical list?",
      "How many days are there in a week?",
      "How many continents are there on Earth?",
      "How many colors are there in the rainbow?",
      "How many Harry Potter books are there in the series?",
      "How many innings are there in a standard baseball game?",
      "How many notes are there in a diatonic musical scale?",
    ],
  },
  {
    id: "8",
    value: 8,
    riddles: [
      "In computing, how many bits are in a byte?",
      "In gaming, how many bits are in a byte?",
      "How many legs does a spider typically have?",
      "How many sides does an octagon have?",
      "How many legs does an octopus typically have?",
      "How many arms does a starfish typically have?",
      "How many ounces are there in a cup?",
      "In a standard game of pool, what is the number of the last ball a player needs to sink to win?",
    ],
  },
  {
    id: "9",
    value: 9,
    riddles: [
      "In literature, how many circles of Hell are depicted in Dante's 'Inferno'?",
      "In mythology, how many Muses were there in Greek mythology?",
      "How many innings are there in a standard game of baseball?",
      "How many lives does a cat typically have in folklore?",
      "How many provinces are there in Canada?",
      "How many justices serve on the US Supreme Court?",
      "How many provinces are there in South Africa?",
      "How many months typically have 30 days?",
    ],
  },
  {
    id: "10",
    value: 10,
    riddles: [
      "In botany, how many stamens are there in a decamerous flower?",
      "In art, how many works are there in Claude Monet's series 'Water Lilies'?",
      "How many toes does a human typically have in total?",
      "How many provinces and territories are there in Canada?",
      "How many official Disney princesses are there?",
      "How many players are on the field for a team in soccer?",
      "How many amendments are in the US Bill of Rights?",
      "How many cents are in a dime?",
    ],
  },
];
